package Game;

public enum Status {
    MAXWEIGHT, PICKUP_SUCCESS, ITEM_NOT_EXIST, ARMOUR_EQUIP_SUCCESS, WEAPON_EQUIP_SUCCESS, CANNOT_EQUIP,
    EAT_SUCCESS, EAT_FAIL, EAT_FAIL_FULLHP, NO_WEAPON_EQUIPPED, OUT_OF_AMMO, CAN_USE_WEAPON
}