package Game;

public enum Status {
    MAXWEIGHT, PICKUP_SUCCESS, ITEM_NOT_EXIST, DEATH, ALIVE, ARMOUR_EQUIP_SUCCESS, WEAPON_EQUIP_SUCCESS, CANNOT_EQUIP,
    EAT_SUCCESS, EAT_FAIL, EAT_FAIL_FULLHP, NO_WEAPON_EQUIPPED, PLAYER_ATTACK_SUCCESS, ENEMY_DEAD, NO_ENEMY_IN_ROOM, OUT_OF_AMMO, CAN_USE_WEAPON;
}